name: PalWorld

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    strategy:
      matrix:
        os: [ 'ubuntu-latest' ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4

      - name: Install Containerd
        run: chmod +x ./script/containerd/install_containerd.sh && ./script/containerd/install_containerd.sh

      - name: Install PalWorld
        run: chmod +x ./script/*.sh && ./script/install_pal.sh