name: PalWorld

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    strategy:
      matrix:
        os: [ 'ubuntu-latest' ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4

      - name: Install Containerd
        run: cd ./script/containerd && chmod +x install_containerd.sh && ./install_containerd.sh

      - name: Install PalWorld
        run: cd ./script && chmod +x *.sh && ./install_pal.sh

      - name: Install Sync Server
        run: cd ./script/sync && chmod +x *.sh && ./sync_server.sh

      - name: Install Sync Client
        run: cd ./script/sync && ./sync_client.sh